jar {
    manifest {
        attributes 'Main-Class': 'j.shop.app.ShopApplication'
    }

    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }

    processResources {
        into('WEB-INF') {
            from 'src/main/resources'
        }
    }
}


dependencies {
    implementation project(":j-spring-framework-core")
    testImplementation("org.apache.httpcomponents:httpclient:4.5.9")
}
